app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
    parser-delay: 600s

  stack-overflow:
    default-url: https://api.stackexchange.com/2.3/

  github:
    default-url: https://api.github.com/


    #add another Link there as smth-record-class: first-url: value
    #Then redact ApplicationConfig
spring:
  application:
    name: scrapper

server:
  port: 8070

logging:
  config: classpath:log4j2-plain.xml
scrapper:
  baseUrl: http://localhost:8080
springdoc:
  swagger-ui:
    path: /swagger-ui

