app:
  database-access-type:
    jdbc
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
    parser-delay: 600s

  list-of-links-supported:
    stackoverflow: stackoverflow.com
    github: github.com


  api:
    bot-url: http://localhost:8090


    #add another Link there as smth-record-class: first-url: value
    #Then redact ApplicationConfig
spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
scrapper:
  baseUrl: http://localhost:8090
springdoc:
  swagger-ui:
    path: /swagger-ui

