app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s

  stack-overflow-url:
    default-url: https://api.stackexchange.com/2.3/

  github-url:
    default-url: https://api.github.com/

    #add another Link there as smth-record-class: first-url: value
    #Then redact ApplicationConfig
spring:
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

