app:
  database-access-type:
    jdbc
  scheduler:
    enable: true
    interval: 100s
    force-check-delay: 10s
    parser-delay: 600s

  list-of-links-supported:
    stackoverflow: stackoverflow.com
    github: github.com


  api:
    bot-url: http://localhost:8090
  bot:
    400:
      type: constant
      delay: PT1S
      max-attempts: 3



  stackoverflow:
    400:
      type: linear
      delay: PT1S
      max-attempts: 3


  github:
    400:
      type: exponential
      delay: PT1S
      max-attempts: 3

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false

  datasource:

    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
scrapper:
  baseUrl: http://localhost:8090
springdoc:
  swagger-ui:
    path: /swagger-ui

