app:
  database-access-type:
    jdbc
  scheduler:
    enable: true
    interval: 100s
    force-check-delay: 10s
    parser-delay: 600s

  list-of-links-supported:
    stackoverflow: stackoverflow.com
    github: github.com


  api:
    bot-url: http://localhost:8090
    github-token: ${GITHUB_TOKEN}
    stackoverflow-key: ${STACKOVERFLOW_KEY}
    stackoverflow-access-token: ${STACKOVERFLOW_ACCESS_TOKEN}
  bot:
    retry-type: constant
    retry-count: 3
    delay: 4s
    retry-codes: INTERNAL_SERVER_ERROR, BAD_GATEWAY, INSUFFICIENT_STORAGE, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT, TOO_MANY_REQUESTS


  stackoverflow:
    retry-type: linear
    retry-count: 3
    delay: 4s
    retry-codes: INTERNAL_SERVER_ERROR, BAD_GATEWAY, INSUFFICIENT_STORAGE, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT, TOO_MANY_REQUESTS



  github:
    retry-type: exponential
    retry-count: 3
    delay: 4s
    retry-codes: INTERNAL_SERVER_ERROR, BAD_GATEWAY, INSUFFICIENT_STORAGE, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT, TOO_MANY_REQUESTS
  kafka:
    bootstrap-servers: localhost:9092
    topic-name: updates
  use-queue: true
spring:
  application:
    name: scrapper
  liquibase:
    enabled: false

  datasource:

    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
  level:
    org.springframework.web: DEBUG
scrapper:
  base-url: http://localhost:8090
springdoc:
  swagger-ui:
    path: /swagger-ui

