app:
  telegram-token: ${TELEGRAM_TOKEN}
  api:
    scrapper-url: http://localhost:8080
  kafka:
    topic-name: updates
    consumer-group-id: bot
    bootstrap-server: localhost:9092
    type-mapping: edu.java.data.request.LinkUpdateRequest:edu.java.data.request.LinkUpdateRequest
    dlq-topic-name: badResponse

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090
management:
  metrics:
    tags:
      application: ${spring.application.name}

  server:
    port: 8001
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
      path-mapping:
        prometheus: /metrics
      base-path: '/'

  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  config: classpath:log4j2-plain.xml
api:
  scrapper:
    baseUrl: http://localhost:8080

springdoc:
  swagger-ui:
    path: /swagger-ui
