app:
  telegram-token: ${TELEGRAM_TOKEN}
  api:
    scrapper-url: http://localhost:8080
  kafka:
    topic-name: updates
    consumer-group-id: bot
    bootstrap-server: localhost:9092
    type-mapping: edu.java.scrapper.dto.response.LinkUpdateResponse:edu.java.bot.dto.response.LinkUpdateResponse
    dlq-topic-name: badResponse
  scrapper:
    retry-type: linear
    retry-count: 3
    delay: 4s
    retry-codes: INTERNAL_SERVER_ERROR, BAD_GATEWAY, INSUFFICIENT_STORAGE, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT, TOO_MANY_REQUESTS

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
api:
  scrapper:
    baseUrl: http://localhost:8080

springdoc:
  swagger-ui:
    path: /swagger-ui
